/*     */ package net.minecraft.client.model.geom;
/*     */ 
/*     */ import com.google.common.collect.ImmutableMap;
/*     */ import java.util.List;
/*     */ import java.util.Map;
/*     */ import java.util.stream.Collectors;
/*     */ import net.minecraft.client.model.AllayModel;
/*     */ import net.minecraft.client.model.ArmorStandArmorModel;
/*     */ import net.minecraft.client.model.ArmorStandModel;
/*     */ import net.minecraft.client.model.AxolotlModel;
/*     */ import net.minecraft.client.model.BatModel;
/*     */ import net.minecraft.client.model.BeeModel;
/*     */ import net.minecraft.client.model.BlazeModel;
/*     */ import net.minecraft.client.model.BoatModel;
/*     */ import net.minecraft.client.model.BookModel;
/*     */ import net.minecraft.client.model.BreezeModel;
/*     */ import net.minecraft.client.model.CamelModel;
/*     */ import net.minecraft.client.model.ChestBoatModel;
/*     */ import net.minecraft.client.model.ChestRaftModel;
/*     */ import net.minecraft.client.model.ChestedHorseModel;
/*     */ import net.minecraft.client.model.ChickenModel;
/*     */ import net.minecraft.client.model.CodModel;
/*     */ import net.minecraft.client.model.CowModel;
/*     */ import net.minecraft.client.model.CreeperModel;
/*     */ import net.minecraft.client.model.DolphinModel;
/*     */ import net.minecraft.client.model.DrownedModel;
/*     */ import net.minecraft.client.model.ElytraModel;
/*     */ import net.minecraft.client.model.EndermanModel;
/*     */ import net.minecraft.client.model.EndermiteModel;
/*     */ import net.minecraft.client.model.EvokerFangsModel;
/*     */ import net.minecraft.client.model.FoxModel;
/*     */ import net.minecraft.client.model.FrogModel;
/*     */ import net.minecraft.client.model.GhastModel;
/*     */ import net.minecraft.client.model.GoatModel;
/*     */ import net.minecraft.client.model.GuardianModel;
/*     */ import net.minecraft.client.model.HoglinModel;
/*     */ import net.minecraft.client.model.HorseModel;
/*     */ import net.minecraft.client.model.HumanoidArmorModel;
/*     */ import net.minecraft.client.model.HumanoidModel;
/*     */ import net.minecraft.client.model.IllagerModel;
/*     */ import net.minecraft.client.model.IronGolemModel;
/*     */ import net.minecraft.client.model.LavaSlimeModel;
/*     */ import net.minecraft.client.model.LeashKnotModel;
/*     */ import net.minecraft.client.model.LlamaModel;
/*     */ import net.minecraft.client.model.LlamaSpitModel;
/*     */ import net.minecraft.client.model.MinecartModel;
/*     */ import net.minecraft.client.model.OcelotModel;
/*     */ import net.minecraft.client.model.PandaModel;
/*     */ import net.minecraft.client.model.ParrotModel;
/*     */ import net.minecraft.client.model.PhantomModel;
/*     */ import net.minecraft.client.model.PigModel;
/*     */ import net.minecraft.client.model.PiglinHeadModel;
/*     */ import net.minecraft.client.model.PiglinModel;
/*     */ import net.minecraft.client.model.PlayerModel;
/*     */ import net.minecraft.client.model.PolarBearModel;
/*     */ import net.minecraft.client.model.PufferfishBigModel;
/*     */ import net.minecraft.client.model.PufferfishMidModel;
/*     */ import net.minecraft.client.model.PufferfishSmallModel;
/*     */ import net.minecraft.client.model.RabbitModel;
/*     */ import net.minecraft.client.model.RaftModel;
/*     */ import net.minecraft.client.model.RavagerModel;
/*     */ import net.minecraft.client.model.SalmonModel;
/*     */ import net.minecraft.client.model.SheepFurModel;
/*     */ import net.minecraft.client.model.SheepModel;
/*     */ import net.minecraft.client.model.ShieldModel;
/*     */ import net.minecraft.client.model.ShulkerBulletModel;
/*     */ import net.minecraft.client.model.ShulkerModel;
/*     */ import net.minecraft.client.model.SilverfishModel;
/*     */ import net.minecraft.client.model.SkeletonModel;
/*     */ import net.minecraft.client.model.SkullModel;
/*     */ import net.minecraft.client.model.SlimeModel;
/*     */ import net.minecraft.client.model.SnifferModel;
/*     */ import net.minecraft.client.model.SnowGolemModel;
/*     */ import net.minecraft.client.model.SpiderModel;
/*     */ import net.minecraft.client.model.SquidModel;
/*     */ import net.minecraft.client.model.StriderModel;
/*     */ import net.minecraft.client.model.TadpoleModel;
/*     */ import net.minecraft.client.model.TridentModel;
/*     */ import net.minecraft.client.model.TropicalFishModelA;
/*     */ import net.minecraft.client.model.TropicalFishModelB;
/*     */ import net.minecraft.client.model.TurtleModel;
/*     */ import net.minecraft.client.model.VexModel;
/*     */ import net.minecraft.client.model.VillagerModel;
/*     */ import net.minecraft.client.model.WardenModel;
/*     */ import net.minecraft.client.model.WindChargeModel;
/*     */ import net.minecraft.client.model.WitchModel;
/*     */ import net.minecraft.client.model.WitherBossModel;
/*     */ import net.minecraft.client.model.WolfModel;
/*     */ import net.minecraft.client.model.ZombieVillagerModel;
/*     */ import net.minecraft.client.model.dragon.DragonHeadModel;
/*     */ import net.minecraft.client.model.geom.builders.CubeDeformation;
/*     */ import net.minecraft.client.model.geom.builders.LayerDefinition;
/*     */ import net.minecraft.client.renderer.blockentity.BannerRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.BedRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.BellRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.ChestRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.ConduitRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
/*     */ import net.minecraft.client.renderer.blockentity.SignRenderer;
/*     */ import net.minecraft.client.renderer.entity.EndCrystalRenderer;
/*     */ import net.minecraft.client.renderer.entity.EnderDragonRenderer;
/*     */ import net.minecraft.client.renderer.entity.WitherSkullRenderer;
/*     */ import net.minecraft.client.renderer.entity.layers.SpinAttackEffectLayer;
/*     */ import net.minecraft.world.entity.vehicle.Boat;
/*     */ import net.minecraft.world.level.block.state.properties.WoodType;
/*     */ 
/*     */ 
/*     */ public class LayerDefinitions
/*     */ {
/* 111 */   private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
/* 112 */   private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
/* 113 */   private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);
/*     */   
/*     */   public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
/* 116 */     ImmutableMap.Builder<ModelLayerLocation, LayerDefinition> $$0 = ImmutableMap.builder();
/*     */     
/* 118 */     LayerDefinition $$1 = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
/* 119 */     LayerDefinition $$2 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION), 64, 32);
/* 120 */     LayerDefinition $$3 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(new CubeDeformation(1.02F)), 64, 32);
/* 121 */     LayerDefinition $$4 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION), 64, 32);
/* 122 */     LayerDefinition $$5 = MinecartModel.createBodyLayer();
/* 123 */     LayerDefinition $$6 = SkullModel.createMobHeadLayer();
/* 124 */     LayerDefinition $$7 = LayerDefinition.create(HorseModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
/* 125 */     LayerDefinition $$8 = IllagerModel.createBodyLayer();
/* 126 */     LayerDefinition $$9 = CowModel.createBodyLayer();
/* 127 */     LayerDefinition $$10 = LayerDefinition.create(OcelotModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
/* 128 */     LayerDefinition $$11 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
/* 129 */     LayerDefinition $$12 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
/* 130 */     LayerDefinition $$13 = SkullModel.createHumanoidHeadLayer();
/* 131 */     LayerDefinition $$14 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
/* 132 */     LayerDefinition $$15 = StriderModel.createBodyLayer();
/* 133 */     LayerDefinition $$16 = HoglinModel.createBodyLayer();
/* 134 */     LayerDefinition $$17 = SkeletonModel.createBodyLayer();
/* 135 */     LayerDefinition $$18 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64);
/* 136 */     LayerDefinition $$19 = SpiderModel.createSpiderBodyLayer();
/*     */     
/* 138 */     $$0.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
/* 139 */     $$0.put(ModelLayers.ARMOR_STAND, ArmorStandModel.createBodyLayer());
/* 140 */     $$0.put(ModelLayers.ARMOR_STAND_INNER_ARMOR, ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
/* 141 */     $$0.put(ModelLayers.ARMOR_STAND_OUTER_ARMOR, ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION));
/* 142 */     $$0.put(ModelLayers.AXOLOTL, AxolotlModel.createBodyLayer());
/* 143 */     $$0.put(ModelLayers.BANNER, BannerRenderer.createBodyLayer());
/* 144 */     $$0.put(ModelLayers.BAT, BatModel.createBodyLayer());
/* 145 */     $$0.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
/* 146 */     $$0.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
/* 147 */     $$0.put(ModelLayers.BEE, BeeModel.createBodyLayer());
/* 148 */     $$0.put(ModelLayers.BELL, BellRenderer.createBodyLayer());
/* 149 */     $$0.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
/* 150 */     $$0.put(ModelLayers.BOOK, BookModel.createBodyLayer());
/* 151 */     $$0.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer());
/* 152 */     $$0.put(ModelLayers.BREEZE_EYES, BreezeModel.createEyesLayer());
/* 153 */     $$0.put(ModelLayers.BREEZE_WIND, BreezeModel.createWindBodyLayer());
/* 154 */     $$0.put(ModelLayers.CAT, $$10);
/* 155 */     $$0.put(ModelLayers.CAT_COLLAR, LayerDefinition.create(OcelotModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32));
/* 156 */     $$0.put(ModelLayers.CAMEL, CamelModel.createBodyLayer());
/* 157 */     $$0.put(ModelLayers.CAVE_SPIDER, $$19);
/* 158 */     $$0.put(ModelLayers.CHEST, ChestRenderer.createSingleBodyLayer());
/* 159 */     $$0.put(ModelLayers.CHEST_MINECART, $$5);
/* 160 */     $$0.put(ModelLayers.CHICKEN, ChickenModel.createBodyLayer());
/* 161 */     $$0.put(ModelLayers.COD, CodModel.createBodyLayer());
/* 162 */     $$0.put(ModelLayers.COMMAND_BLOCK_MINECART, $$5);
/* 163 */     $$0.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
/* 164 */     $$0.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
/* 165 */     $$0.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
/* 166 */     $$0.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
/* 167 */     $$0.put(ModelLayers.COW, $$9);
/* 168 */     $$0.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
/* 169 */     $$0.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
/* 170 */     $$0.put(ModelLayers.CREEPER_HEAD, $$6);
/* 171 */     $$0.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
/* 172 */     $$0.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
/* 173 */     $$0.put(ModelLayers.DOLPHIN, DolphinModel.createBodyLayer());
/* 174 */     $$0.put(ModelLayers.DONKEY, ChestedHorseModel.createBodyLayer());
/* 175 */     $$0.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestRenderer.createDoubleBodyLeftLayer());
/* 176 */     $$0.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestRenderer.createDoubleBodyRightLayer());
/* 177 */     $$0.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
/* 178 */     $$0.put(ModelLayers.DROWNED, DrownedModel.createBodyLayer(CubeDeformation.NONE));
/* 179 */     $$0.put(ModelLayers.DROWNED_INNER_ARMOR, $$4);
/* 180 */     $$0.put(ModelLayers.DROWNED_OUTER_ARMOR, $$4);
/* 181 */     $$0.put(ModelLayers.DROWNED_OUTER_LAYER, DrownedModel.createBodyLayer(new CubeDeformation(0.25F)));
/* 182 */     $$0.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createBodyLayer());
/* 183 */     $$0.put(ModelLayers.ELYTRA, ElytraModel.createLayer());
/* 184 */     $$0.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
/* 185 */     $$0.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
/* 186 */     $$0.put(ModelLayers.ENDER_DRAGON, EnderDragonRenderer.createBodyLayer());
/* 187 */     $$0.put(ModelLayers.END_CRYSTAL, EndCrystalRenderer.createBodyLayer());
/* 188 */     $$0.put(ModelLayers.EVOKER, $$8);
/* 189 */     $$0.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
/* 190 */     $$0.put(ModelLayers.FOX, FoxModel.createBodyLayer());
/* 191 */     $$0.put(ModelLayers.FROG, FrogModel.createBodyLayer());
/* 192 */     $$0.put(ModelLayers.FURNACE_MINECART, $$5);
/* 193 */     $$0.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
/* 194 */     $$0.put(ModelLayers.GIANT, $$1);
/* 195 */     $$0.put(ModelLayers.GIANT_INNER_ARMOR, $$4);
/* 196 */     $$0.put(ModelLayers.GIANT_OUTER_ARMOR, $$2);
/* 197 */     $$0.put(ModelLayers.GLOW_SQUID, SquidModel.createBodyLayer());
/* 198 */     $$0.put(ModelLayers.GOAT, GoatModel.createBodyLayer());
/* 199 */     $$0.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
/* 200 */     $$0.put(ModelLayers.HOGLIN, $$16);
/* 201 */     $$0.put(ModelLayers.HOPPER_MINECART, $$5);
/* 202 */     $$0.put(ModelLayers.HORSE, $$7);
/* 203 */     $$0.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(HorseModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
/* 204 */     $$0.put(ModelLayers.HUSK, $$1);
/* 205 */     $$0.put(ModelLayers.HUSK_INNER_ARMOR, $$4);
/* 206 */     $$0.put(ModelLayers.HUSK_OUTER_ARMOR, $$2);
/* 207 */     $$0.put(ModelLayers.ILLUSIONER, $$8);
/* 208 */     $$0.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
/* 209 */     $$0.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
/* 210 */     $$0.put(ModelLayers.LLAMA, $$14);
/* 211 */     $$0.put(ModelLayers.LLAMA_DECOR, LlamaModel.createBodyLayer(new CubeDeformation(0.5F)));
/* 212 */     $$0.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
/* 213 */     $$0.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
/* 214 */     $$0.put(ModelLayers.MINECART, $$5);
/* 215 */     $$0.put(ModelLayers.MOOSHROOM, $$9);
/* 216 */     $$0.put(ModelLayers.MULE, ChestedHorseModel.createBodyLayer());
/* 217 */     $$0.put(ModelLayers.OCELOT, $$10);
/* 218 */     $$0.put(ModelLayers.PANDA, PandaModel.createBodyLayer());
/* 219 */     $$0.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
/* 220 */     $$0.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
/* 221 */     $$0.put(ModelLayers.PIG, PigModel.createBodyLayer(CubeDeformation.NONE));
/* 222 */     $$0.put(ModelLayers.PIG_SADDLE, PigModel.createBodyLayer(new CubeDeformation(0.5F)));
/* 223 */     $$0.put(ModelLayers.PIGLIN, $$11);
/* 224 */     $$0.put(ModelLayers.PIGLIN_INNER_ARMOR, $$4);
/* 225 */     $$0.put(ModelLayers.PIGLIN_OUTER_ARMOR, $$3);
/* 226 */     $$0.put(ModelLayers.PIGLIN_BRUTE, $$11);
/* 227 */     $$0.put(ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, $$4);
/* 228 */     $$0.put(ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, $$3);
/* 229 */     $$0.put(ModelLayers.PIGLIN_HEAD, $$12);
/* 230 */     $$0.put(ModelLayers.PILLAGER, $$8);
/* 231 */     $$0.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
/* 232 */     $$0.put(ModelLayers.PLAYER_HEAD, $$13);
/* 233 */     $$0.put(ModelLayers.PLAYER_INNER_ARMOR, $$4);
/* 234 */     $$0.put(ModelLayers.PLAYER_OUTER_ARMOR, $$2);
/* 235 */     $$0.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
/* 236 */     $$0.put(ModelLayers.PLAYER_SLIM_INNER_ARMOR, $$4);
/* 237 */     $$0.put(ModelLayers.PLAYER_SLIM_OUTER_ARMOR, $$2);
/* 238 */     $$0.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectLayer.createLayer());
/* 239 */     $$0.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer());
/* 240 */     $$0.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
/* 241 */     $$0.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
/* 242 */     $$0.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
/* 243 */     $$0.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer());
/* 244 */     $$0.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
/* 245 */     $$0.put(ModelLayers.SALMON, SalmonModel.createBodyLayer());
/* 246 */     $$0.put(ModelLayers.SHEEP, SheepModel.createBodyLayer());
/* 247 */     $$0.put(ModelLayers.SHEEP_FUR, SheepFurModel.createFurLayer());
/* 248 */     $$0.put(ModelLayers.SHIELD, ShieldModel.createLayer());
/* 249 */     $$0.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
/* 250 */     $$0.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
/* 251 */     $$0.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
/* 252 */     $$0.put(ModelLayers.SKELETON, $$17);
/* 253 */     $$0.put(ModelLayers.SKELETON_INNER_ARMOR, $$4);
/* 254 */     $$0.put(ModelLayers.SKELETON_OUTER_ARMOR, $$2);
/* 255 */     $$0.put(ModelLayers.SKELETON_HORSE, $$7);
/* 256 */     $$0.put(ModelLayers.SKELETON_SKULL, $$6);
/* 257 */     $$0.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
/* 258 */     $$0.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
/* 259 */     $$0.put(ModelLayers.SNIFFER, SnifferModel.createBodyLayer());
/* 260 */     $$0.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
/* 261 */     $$0.put(ModelLayers.SPAWNER_MINECART, $$5);
/* 262 */     $$0.put(ModelLayers.SPIDER, $$19);
/* 263 */     $$0.put(ModelLayers.SQUID, SquidModel.createBodyLayer());
/* 264 */     $$0.put(ModelLayers.STRAY, $$17);
/* 265 */     $$0.put(ModelLayers.STRAY_INNER_ARMOR, $$4);
/* 266 */     $$0.put(ModelLayers.STRAY_OUTER_ARMOR, $$2);
/* 267 */     $$0.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
/* 268 */     $$0.put(ModelLayers.STRIDER, $$15);
/* 269 */     $$0.put(ModelLayers.STRIDER_SADDLE, $$15);
/* 270 */     $$0.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
/* 271 */     $$0.put(ModelLayers.TNT_MINECART, $$5);
/* 272 */     $$0.put(ModelLayers.TRADER_LLAMA, $$14);
/* 273 */     $$0.put(ModelLayers.TRIDENT, TridentModel.createLayer());
/* 274 */     $$0.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
/* 275 */     $$0.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
/* 276 */     $$0.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
/* 277 */     $$0.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
/* 278 */     $$0.put(ModelLayers.TURTLE, TurtleModel.createBodyLayer());
/* 279 */     $$0.put(ModelLayers.VEX, VexModel.createBodyLayer());
/* 280 */     $$0.put(ModelLayers.VILLAGER, $$18);
/* 281 */     $$0.put(ModelLayers.VINDICATOR, $$8);
/* 282 */     $$0.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
/* 283 */     $$0.put(ModelLayers.WANDERING_TRADER, $$18);
/* 284 */     $$0.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
/* 285 */     $$0.put(ModelLayers.WITCH, WitchModel.createBodyLayer());
/* 286 */     $$0.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
/* 287 */     $$0.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
/* 288 */     $$0.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
/* 289 */     $$0.put(ModelLayers.WITHER_SKELETON, $$17);
/* 290 */     $$0.put(ModelLayers.WITHER_SKELETON_INNER_ARMOR, $$4);
/* 291 */     $$0.put(ModelLayers.WITHER_SKELETON_OUTER_ARMOR, $$2);
/* 292 */     $$0.put(ModelLayers.WITHER_SKELETON_SKULL, $$6);
/* 293 */     $$0.put(ModelLayers.WOLF, WolfModel.createBodyLayer());
/* 294 */     $$0.put(ModelLayers.ZOGLIN, $$16);
/* 295 */     $$0.put(ModelLayers.ZOMBIE, $$1);
/* 296 */     $$0.put(ModelLayers.ZOMBIE_INNER_ARMOR, $$4);
/* 297 */     $$0.put(ModelLayers.ZOMBIE_OUTER_ARMOR, $$2);
/* 298 */     $$0.put(ModelLayers.ZOMBIE_HEAD, $$13);
/* 299 */     $$0.put(ModelLayers.ZOMBIE_HORSE, $$7);
/* 300 */     $$0.put(ModelLayers.ZOMBIE_VILLAGER, ZombieVillagerModel.createBodyLayer());
/* 301 */     $$0.put(ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
/* 302 */     $$0.put(ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
/* 303 */     $$0.put(ModelLayers.ZOMBIFIED_PIGLIN, $$11);
/* 304 */     $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, $$4);
/* 305 */     $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, $$3);
/*     */     
/* 307 */     LayerDefinition $$20 = BoatModel.createBodyModel();
/* 308 */     LayerDefinition $$21 = ChestBoatModel.createBodyModel();
/* 309 */     LayerDefinition $$22 = RaftModel.createBodyModel();
/* 310 */     LayerDefinition $$23 = ChestRaftModel.createBodyModel();
/* 311 */     for (Boat.Type $$24 : Boat.Type.values()) {
/* 312 */       if ($$24 == Boat.Type.BAMBOO) {
/* 313 */         $$0.put(ModelLayers.createBoatModelName($$24), $$22);
/* 314 */         $$0.put(ModelLayers.createChestBoatModelName($$24), $$23);
/*     */       } else {
/* 316 */         $$0.put(ModelLayers.createBoatModelName($$24), $$20);
/* 317 */         $$0.put(ModelLayers.createChestBoatModelName($$24), $$21);
/*     */       } 
/*     */     } 
/*     */     
/* 321 */     LayerDefinition $$25 = SignRenderer.createSignLayer();
/* 322 */     WoodType.values().forEach($$2 -> $$0.put(ModelLayers.createSignModelName($$2), $$1));
/*     */     
/* 324 */     LayerDefinition $$26 = HangingSignRenderer.createHangingSignLayer();
/* 325 */     WoodType.values().forEach($$2 -> $$0.put(ModelLayers.createHangingSignModelName($$2), $$1));
/*     */     
/* 327 */     ImmutableMap<ModelLayerLocation, LayerDefinition> $$27 = $$0.build();
/* 328 */     List<ModelLayerLocation> $$28 = (List<ModelLayerLocation>)ModelLayers.getKnownLocations().filter($$1 -> !$$0.containsKey($$1)).collect(Collectors.toList());
/* 329 */     if (!$$28.isEmpty()) {
/* 330 */       throw new IllegalStateException("Missing layer definitions: " + $$28);
/*     */     }
/* 332 */     return (Map<ModelLayerLocation, LayerDefinition>)$$27;
/*     */   }
/*     */ }


/* Location:              C:\Users\Xiao\Downloads\output\client_deobfuscated.jar!\net\minecraft\client\model\geom\LayerDefinitions.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */